### ISSUE TITLE
uses

### ISSUE THREAD

**Issue by tjoozey** [neographophobic/autoMunkiImporter#1]
Hi, I would like to send a memo to the creators of this script.

I installed the .pkg through mac osx - running "munkiimport" in terminal does not provide me with any helping tool.

I plan to develop a simple MAC OSX app using autominkilimporter. Please let me know what this script does, and how I can import it to a xcode iOS6 project.

Thx

**Comment by neographophobic** [comment]
Auto Munki Importer utilises munkiimport, it doesn't modify it or change it in any way. To use Auto Munki Importer run "autoMunkiImporter.pl" on the command line with the appropriate options.

You can find additional information on how to use Auto Munki Importer via  http://neographophobic.github.com/autoMunkiImporter/index.html or by running "man autoMunkiImporter.pl".

**Comment by tjoozey** [comment]
|ruby-1.9.3-p194| Tylers-MacBook-Pro in ~/Desktop/code/autoMunkiImporter
± |master ✓| → python autoMunkiImporter.pl
  File "autoMunkiImporter.pl", line 41
    use strict;
             ^
SyntaxError: invalid syntax

## 

Tyler Johnson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by neographophobic** [comment]
The script is written in Perl, not Python. To run it all you need to do is run "/usr/local/autoMunkiImporter/autoMunkiImporter.pl" from the command line without the quotes. You should look look at http://neographophobic.github.com/autoMunkiImporter/configuration.html, as the email settings will need to be changed before you can successfully run the script.

**Comment by tjoozey** [comment]
|ruby-1.9.3-p194| Tylers-MacBook-Pro in ~/Desktop/code/autoMunkiImporter
± |master ✓| → perl autoMunkiImporter.pl
[WARNING] Can't write "

###################################################" to log file "/Library/Logs/autoMunkiImporter/autoMunkiImporter.log"
[WARNING] Can't write "Checking Perl Dependencies" to log file "/Library/Logs/autoMunkiImporter/autoMunkiImporter.log"
[WARNING] Can't write "Attempting to read Default Settings plist /Library/Application Support/autoMunkiImporter/_DefaultSettings.plist" to log file "/Library/Logs/autoMunkiImporter/autoMunkiImporter.log"
[WARNING] Can't write "Checking Default Settings plist contains required keys" to log file "/Library/Logs/autoMunkiImporter/autoMunkiImporter.log"
[WARNING] Can't write "Key: smtpServer does not have an appropriate value in the default settings plist. Exiting..." to log file "/Library/Logs/autoMunkiImporter/autoMunkiImporter.log"
[ERROR] Key: smtpServer does not have an appropriate value in the default settings plist. Exiting...

## 

Tyler Johnson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by neographophobic** [comment]
The code requires permissions to write to /Library/Logs/autoMunkiImporter by default which it doesn't have (that's what all of the [WARNING] messages are about. Please ensure the directory exists and the user your running the script as has permissions to write to it.

The final [ERROR] message is because you haven't changed the default values in the default settings plist. If you are using the installer package the plist will be at /Library/Application Support/autoMunkiImporter/_DefaultConfig.plist. You will need to change the values for "fromAddress", "smtpServer", and "toAddress".

**Comment by neographophobic** [comment]
I'm closing old issues. I suggest that you look at [AutoPkg](https://github.com/autopkg/autopkg) for any future requirements for automating Munki.
