### ISSUE TITLE
Adobe updates fail

### ISSUE THREAD

**Issue by bestmacs** [neographophobic/autoMunkiImporter#2]
Adam, first off thank you for sharing this script.  It's been working great here.  I'd love to see more example plists - like for example I can't get CyberDuck, Dropbox, nor Flip4Mac to play ball.

We did have Adobe Reader and Flash working just fine then recently they started throwing errors after checking on a version it already completed.  In other words, AdobeReader 11.0.3 downloaded and imported fine, but subsequent daily checks of 11.0.3 throw this error.

(we use OpenDNS so it looks like the script was trying to find a bad or dead URL):
Modification date of download not found, indicating a problem.

The URL http://www.website-unavailable.com/?wc=EWJvEwBmBRJEGxV0AhYKHA==&url=Content%2DType returned the following headers 
% Total % Received % Xferd Average Speed Time Time Time Current 
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 
HTTP/1.0 200 OK

Cache-Control: no-cache, must-revalidate

Expires: Mon, 26 Jul 1997 05:00:00 GMT

Content-Type: text/html; charset=utf-8

Pragma: no-cache

Set-Cookie: OUS=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=.opendns.com

Content-Length: 0

Connection: close

Date: Wed, 15 May 2013 09:04:33 GMT

Server: OpenDNS Guide

. Script terminated...

Here's the plist:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>autoMunkiImporter</key>
    <dict>
        <key>Import History</key>
        <dict>
            <key>11.0.02</key>
            <dict>
                <key>InitialURL</key>
                <string>http://get.adobe.com/reader/</string>
                <key>finalURL</key>
                <string>http://ardownload.adobe.com/pub/adobe/reader/mac/11.x/11.0.02/en_US/AdbeRdr11002_en_US.dmg</string>
                <key>importDate</key>
                <date>2013-04-11T16:35:41Z</date>
                <key>modifiedDate</key>
                <date>2013-02-15T23:30:29Z</date>
                <key>pkginfoPath</key>
                <string>/munkiBiz/pkgsinfo/AdobeReader-11.0.02.plist</string>
            </dict>
        </dict>
        <key>URLToMonitor</key>
        <string>http://get.adobe.com/reader/</string>
        <key>downloadLinkRegex</key>
        <string>Download Now</string>
        <key>emailReports</key>
        <true/>
        <key>itemToImport</key>
        <string>Adobe Reader * Installer.pkg</string>
        <key>lastRunTime</key>
        <date>2013-05-26T12:31:38Z</date>
        <key>lastStatus</key>
        <string>ERROR: Modification date of download not found.</string>
        <key>modifiedDate</key>
        <date>2013-05-11T11:58:33Z</date>
        <key>modifiedDateCorrospoindingVersion</key>
        <string>11.0.03</string>
        <key>munkiimportOptions</key>
        <string>--minimum_os_version "10.5.8"</string>
        <key>name</key>
        <string>AdobeReader</string>
        <key>secondLinkRegex</key>
        <string>location.href\s*=\s*'(.+?)'</string>
        <key>type</key>
        <string>dynamic</string>
    </dict>
    <key>catalogs</key>
    <array>
        <string>testing</string>
    </array>
</dict>
</plist>`

Any idea?

**Comment by neographophobic** [comment]
I suspect Adobe have changed their download pages, which is breaking the scraping I was doing. I'll try to look into it over the next week and see if I can find a solution.

**Comment by neographophobic** [comment]
I'm closing old issues. I suggest that you look at [AutoPkg](https://github.com/autopkg/autopkg) which has support for Adobe products.
