### ISSUE TITLE
Hangs and crashes

### ISSUE THREAD

**Issue by czeranox** [neographophobic/autoMunkiImporter#3]
Hello,

I just installed autoMunkiImporter and I'm pretty impressed thus far. That said, I'm having a minor issue. 

After each time I run the program, if it finds something it needs to build, it will complete it correctly but then hang for roughly 30seconds, then crash out stating "Operation timed out at /Library/Perl/5.12/Mail/Mailer.pm line 158" I have emailReports set to False. I've check the Mailer.pm and have no idea what I'm looking at really. It isn't a huge issue to work around because I can just rerun the program and it will move onto the next file like nothing ever happened but I won't be able to automate it if its crashing like this. Any ideas?

**Comment by neographophobic** [comment]
Hi,

Can you run the following and tell me the results?

perl -MMail::Mailer -e 'print "$Mail::Mailer::VERSION\n"'

Also what version of the OS are you running?

Cheers,
Adam

**Comment by czeranox** [comment]
Should I be running that in a specific directory? Copy pasting that in terminal just makes it sit there. Same result if I throw a ./ in front of it. I'm running 10.8.4 btw. 

Also, I think I may have figured out the issue. I didn't realize that the individual plists have an emailReports value as well. I set them to false but automunki still realizes that it's up to date on everything even though I threw out the logs so I can't really test my theory.

**Comment by neographophobic** [comment]
That command should run the systems installed version of perl, and if it finds the Mail::Mailer module report what version is installed. It doesn't need to be in any specific directory. I suspect that for some reason your install is failing to talk to the SMTP Server that is specified in your _DefaultSettings.plist (via the smtpServer key) when trying to send emails.

The way autoMunkiImporter remembers that it has downloaded an item is that it puts modifiedDate and modifiedDateCorrospoindingVersion keys within the autoMunkiImporter dictionary in the plist. If you want to try a plist and download an existing item you have two options. The prefered version is to run autoMunkiImporter.pl with the --ignoreModDate command line option. You can also remove the modifiedDate and modifiedDateCorrospoindingVersion keys from the plist.

I would recommend setting emailReports to false in each of the data plists you want to run and then trying again with the --ignoreModDate command. Please let me know if this still hangs. I don't have a 10.8.4 box handy at the moment to do further tests.

Cheers,
Adam

**Comment by czeranox** [comment]
Excellent! It works now that I've disabled emailReports on a per plist basis. Thanks for the assistance and telling me about the --ignoreModDate modifier, it's working flawlessly now =)
